package com.ymslx.tag.goods.entity;

import java.util.Date;

public class TagEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.id
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.name
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.style
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.description
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.expire_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.status
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.clean_on_delete
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Integer cleanOnDelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.clean_on_expire
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Integer cleanOnExpire;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.create_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.modifier
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Integer modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.modify_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tag.creator
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    private Integer creator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.id
     *
     * @return the value of tag.id
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.id
     *
     * @param id the value for tag.id
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.name
     *
     * @return the value of tag.name
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.name
     *
     * @param name the value for tag.name
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.style
     *
     * @return the value of tag.style
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.style
     *
     * @param style the value for tag.style
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.description
     *
     * @return the value of tag.description
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.description
     *
     * @param description the value for tag.description
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.expire_time
     *
     * @return the value of tag.expire_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.expire_time
     *
     * @param expireTime the value for tag.expire_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.status
     *
     * @return the value of tag.status
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.status
     *
     * @param status the value for tag.status
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.clean_on_delete
     *
     * @return the value of tag.clean_on_delete
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Integer getCleanOnDelete() {
        return cleanOnDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.clean_on_delete
     *
     * @param cleanOnDelete the value for tag.clean_on_delete
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setCleanOnDelete(Integer cleanOnDelete) {
        this.cleanOnDelete = cleanOnDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.clean_on_expire
     *
     * @return the value of tag.clean_on_expire
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Integer getCleanOnExpire() {
        return cleanOnExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.clean_on_expire
     *
     * @param cleanOnExpire the value for tag.clean_on_expire
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setCleanOnExpire(Integer cleanOnExpire) {
        this.cleanOnExpire = cleanOnExpire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.create_time
     *
     * @return the value of tag.create_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.create_time
     *
     * @param createTime the value for tag.create_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.modifier
     *
     * @return the value of tag.modifier
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Integer getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.modifier
     *
     * @param modifier the value for tag.modifier
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setModifier(Integer modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.modify_time
     *
     * @return the value of tag.modify_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.modify_time
     *
     * @param modifyTime the value for tag.modify_time
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tag.creator
     *
     * @return the value of tag.creator
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tag.creator
     *
     * @param creator the value for tag.creator
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }
}