package com.ymslx.tag.goods.mapper;

import com.ymslx.tag.goods.entity.TagEntity;
import com.ymslx.tag.goods.entity.TagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    long countByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int deleteByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int insert(TagEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int insertSelective(TagEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    List<TagEntity> selectByExample(TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    TagEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int updateByExampleSelective(@Param("row") TagEntity row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int updateByExample(@Param("row") TagEntity row, @Param("example") TagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int updateByPrimaryKeySelective(TagEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tag
     *
     * @mbg.generated Sat Mar 22 13:22:48 CST 2025
     */
    int updateByPrimaryKey(TagEntity row);
}