server:
  port: 8085

spring:
  datasource:
    username: root
    password: Ymslx-2020
    url: jdbc:mysql://localhost:3306/shop?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
      cache: false
      encoding: UTF-8
      mode: HTML
      prefix: classpath:/templates/
      suffix: .html
  application:
    name: tag-goods
  resources:
    static-locations: classpath:/static/, classpath:/public/, classpath:/resources/, classpath:/META-INF/resources/
mybatis:
  mapper-locations: classpath:mapper/*.xml